
CREATE TABLE library_user (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       email text,
       first_name text,
       last_name text,
       display_name text,
       hashed_password text,
       joined timestamptz,
       last_login timestamptz,
       admin boolean
);

CREATE TABLE publication_series (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       title text,
       count int,
       inserted_by bigint REFERENCES library_user(id),
       inserted_at timestamptz,
       updated_by bigint REFERENCES library_user(id),
       updated_at timestamptz
);


CREATE TABLE publication_edition_type (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       publication_type text,
       inserted_by bigint REFERENCES library_user(id),
       inserted_at timestamptz,
       updated_by bigint REFERENCES library_user(id),
       updated_at timestamptz
);

CREATE TABLE publication (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       publication_series_id bigint REFERENCES publication_series(id),
       title text,
       subtitle text,
       language text,
       sort_title text,
       url text,
       private boolean,
       inserted_by bigint REFERENCES library_user(id),
       inserted_at timestamptz,
       updated_by bigint REFERENCES library_user(id),
       updated_at timestamptz
);

CREATE TABLE publication_edition (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       publication_id bigint REFERENCES publication(id),
       publication_year int,
       pages int,
       isbn text,
       type_id bigint REFERENCES publication_edition_type(id),
       private boolean,
       inserted_by bigint REFERENCES library_user(id),
       inserted_at timestamptz,
       updated_by bigint REFERENCES library_user(id),
       updated_at timestamptz
);

CREATE TABLE creator (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       first_name text,
       middle_name text,
       last_name text,
       born date,
       died date,
       private boolean,
       inserted_by bigint REFERENCES library_user(id),
       inserted_at timestamptz,
       updated_by bigint REFERENCES library_user(id),
       updated_at timestamptz
);

CREATE TABLE creator_role (
       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name text,
       inserted_by bigint REFERENCES library_user(id),
       inserted_at timestamptz,
       updated_by bigint REFERENCES library_user(id),
       updated_at timestamptz
);

CREATE TABLE publication_edition_creator (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       publication_edition_id bigint REFERENCES publication_edition(id),
       creator_id bigint REFERENCES creator(id),
       role int REFERENCES creator_role(id),
       inserted_by bigint REFERENCES library_user(id),
       inserted_at timestamptz,
       updated_by bigint REFERENCES library_user(id),
       updated_at timestamptz
);

CREATE TABLE user_quote (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       publication_edition_id bigint REFERENCES publication_edition(id),
       creator_id bigint REFERENCES creator(id),
       user_id bigint REFERENCES library_user(id),
       quote text,
       page text,
       chapter text,
       section text,
       private boolean,
       inserted_at timestamptz,
       updated_at timestamptz
);

CREATE TABLE user_creator_comment (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       creator_id bigint REFERENCES creator(id),
       comment text,
       private boolean,
       inserted_at timestamptz,
       updated_at timestamptz
);

CREATE TABLE user_publication_edition (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       publication_id bigint REFERENCES publication(id),
       user_id bigint REFERENCES library_user(id),
       owned boolean,
       location text,
       purchased date,
       source text,
       private boolean,
       inserted_at timestamptz,
       updated_at timestamptz
);

CREATE TABLE user_publication_edition_read (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       publication_edition_id bigint REFERENCES publication_edition(id),
       user_id bigint REFERENCES library_user(id),
       started date,
       read date,
       finished boolean,
       last_page_read text,
       private boolean,
       inserted_at timestamptz,
       updated_at timestamptz
);

CREATE TABLE user_publication_series_comment (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       publication_series_id bigint REFERENCES publication_series(id),
       user_id bigint REFERENCES library_user(id),
       comment text,
       private boolean,
       inserted_at timestamptz,
       updated_at timestamptz
);

CREATE TABLE user_publication_comment (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       publication_id bigint REFERENCES publication(id),
       user_id bigint REFERENCES library_user(id),
       comment text,
       private boolean,
       inserted_at timestamptz,
       updated_at timestamptz
);

CREATE TABLE user_publication_review (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       user_publication_edition_read_id bigint REFERENCES user_publication_edition_read(id),
       stars int,
       review text,
       private boolean,
       inserted_at timestamptz,
       updated_at timestamptz
);

CREATE TABLE user_quote_comment (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       user_quote_id bigint REFERENCES user_quote(id),
       comment text,
       private boolean,
       inserted_at timestamptz,
       updated_at timestamptz
);

CREATE TABLE library_audit_log (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       event text,
       table_name text,
       inserted_by bigint REFERENCES library_user(id),
       inserted_at timestamptz
);
